# -*- coding: utf-8 -*-
"""Numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKYwMjg8_dFwtEsMDp7zLaEIAQ_cC1yp
"""

!pip install numpy

import numpy as np
list1 = [1, 2, 3, 4, 5]
print(type(list1))
np_arr = np.array(list1)
np_arr
print(type(np.array))

#1 array
np1 = np.array([1, 2, 3, 4, 5])
print(np1.shape)
np2 = np.array([[1, 2, 3],[4, 5, 6]])
np3 = np.array([[[1,2], [4, 5, 6], [7, 8, 9]]])
np1

np4 = np.array([1, 2, 3, 4, 5], dtype=float)
np4

list2 = [num for num in range(10)]
n1 = np.arange(0, 12)
n2 = n1.reshape(2, 6)
n3 = n1.reshape(2, 2, 3)
n3

nv1 = np.arange(5)
print(f"Original Value: {nv1}")
nv2 = nv1.view()
print(f"Original Value: {nv2}")
nv3 = nv1.copy()
print(f"Original Value: {nv3}")

a = np.array([1, 2, 3, 4])
print(np.square(a))

npzero = np.zeros([3, 3, 3], dtype=int)
npfull = np.full([3, 3], 4, dtype=int)
npfull
# npzero

np_i = np.eye(5, dtype=int)
np_i

l_np = np.linspace(1, 100, 5, dtype=int)
l_np

n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([6, 7, 8, 9, 0])
sum = n1 + n2
print(sum)

n1 = np.array([1, 8, 3, 7, 5])
n3 = np.sort(n1)
n3

n1 = np.array([1, 2, 3])
n2 = np.tile(n1, 5)
n3 = np.tile(n1, (3, 1))
n3

import numpy as np
n1 = np.arange(1, 4)
n2 = np.tile(n1, (3, 1))
npfull = np.full([3, 3], 1, dtype=int)
product = n2 * npfull
print(product)

n1 = np.arange(1, 10)
n2 = n1.reshape(3, 3)
npfull = np.full([3, 3], 4, dtype=int)
sum = n2 + npfull
print(sum)

import numpy as np

n1 = np.linspace(1, 33, 9, dtype=int)
n2 = n1.reshape(3, 3)
n3 = np.arange(10, 1, -1)
n4 = n3.reshape(3, 3)
dif = n2 - n4
print(dif)