# -*- coding: utf-8 -*-
"""problem3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9QL53D3oRJI93YySxkMt1YKvRMe34Wx
"""

import pandas as pd

time = pd.read_excel('problem3.xlsx')

df=time
df=df.groupby(['bike_number'],as_index=False)['end_time'].max()
df.sort_values(['end_time'],ascending=False)