# -*- coding: utf-8 -*-
"""flores_johnpatrick_notebook_quiz1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlu7RxVYRoZxpqN3rNeKvKn8LMyp8Gjs
"""

import pandas as pd

# PROBLEM 1

job = pd.read_excel('problem1.xlsx', sheet_name=['worker', 'title'])
merged = pd.merge(job['worker'], job['title'], left_on='worker_id', right_on='worker_ref_id').head()
highest_salary = merged.groupby('worker_title')['salary'].max()
best_paid_title = highest_salary[highest_salary == highest_salary.max()].index
result_df = pd.DataFrame({'best_paid_title': best_paid_title})
result_df



# PROBLEM 2

salary = pd.read_excel('problem2.xlsx')

df = salary
df.groupby('id').max().reset_index()



# PROBLEM 3

time = pd.read_excel('problem3.xlsx')

df=time
df=df.groupby(['bike_number'],as_index=False)['end_time'].max()
df.sort_values(['end_time'],ascending=False)



# PROBLEM 4

popularity = pd.read_excel('problem4.xlsx')

users = pd.concat([popularity['user1'], popularity['user2']])
total_users = len(users.unique())
result = (users.value_counts() / total_users * 100).round(3)
result



# PROBLEM 5

email = pd.read_excel('problem5.xlsx')

user_email = email['from_user'].value_counts().reset_index()
user_email.columns = ['from_user', 'total_emails']
user_email['rank'] = range(1, len(user_email) + 1)
user_email